include:
  - path: ./client/compose.yaml
  - path: ./backend/compose.yaml

services:
  nginx:
    image: nginx:alpine
    container_name: nexus_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nexus_api
      - nexus_app
    networks:
      - nexus_network

networks:
  nexus_network:
